package view;

import java.awt.Container;
import java.awt.GridLayout;
import java.util.ArrayList;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JTextPane;
import model.Ember;

public class FrameView extends javax.swing.JFrame {
    
    private Ember[] emberek;
    private ArrayList<JButton> buttons;
    private JTextPane textPane;
    private GroupLayout layout;

    /**
     * Creates new form FrameView
     */
    public FrameView(Ember[] emberek) {
        this.emberek = emberek;
        this.buttons = new ArrayList();
        this.textPane = new JTextPane();
        initButtons();
    }
    
    private void initButtons() {
        
        Container buttonLayout;

        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        this.setTitle("T_Zh_Ember1");

        this.setSize(480, 480);

        buttonLayout = getContentPane();
        buttonLayout.setLayout(new GridLayout(6, 6));
        
        for (Ember ember : emberek) {
            JButton button = new JButton();
            button.setText(ember.getNev());
            buttonLayout.add(button);
            buttons.add(button);
        }
        
        
        
        buttonLayout.add(this.textPane);
        
    }
    
    public ArrayList<JButton> getButtons() {
        return buttons;
    }

    public void setOutput(String value) {
        textPane.setText(value);
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(jTextPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(202, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
